version: '3.8'

services:
  
  # ========== MONGODB (La base de datos) ==========
  mongodb:

    image: mongo:latest
    container_name: mongodb-jenn
    restart: unless-stopped
    ports:
      - "27017:27017"
    
    # "environment" = variables de entorno (configuración)
    environment:
      MONGO_INITDB_ROOT_USERNAME: jenn        
      MONGO_INITDB_ROOT_PASSWORD: CronistaJenn2025 

    volumes:
      - mongodb_data_jenn:/data/db           
      - ./scripts:/scripts                     
    
    networks:
      - mongodb_network_jenn

  # ========== MONGO EXPRESS (Interfaz visual web) ==========
  mongo-express:
    image: mongo-express:latest
    
    container_name: mongo-express-jenn
    
    restart: unless-stopped

    ports:
      - "8081:8081"
    
    environment:

      ME_CONFIG_MONGODB_ADMINUSERNAME: jenn
      ME_CONFIG_MONGODB_ADMINPASSWORD: CronistaJenn2025
      ME_CONFIG_MONGODB_URL: mongodb://jenn:CronistaJenn2025@mongodb:27017/ 
      ME_CONFIG_BASICAUTH: false
    

    depends_on:
      - mongodb
    
    networks:
      - mongodb_network_jenn

# ========== VOLÚMENES (Almacenamiento persistente) ==========

volumes:
  mongodb_data_jenn:
    driver: local    

# ========== REDES ==========
networks:
  mongodb_network_jenn:
    driver: bridge   